# Generated by Django 4.0.5 on 2022-06-21 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название проекта')),
                ('description', models.TextField(verbose_name='Описание проекта')),
                ('image', models.ImageField(upload_to='', verbose_name='Фото')),
                ('is_active', models.BooleanField(default=False, verbose_name='Проект активен')),
            ],
        ),
    ]
