# Generated by Django 4.0.5 on 2022-06-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='is_active',
        ),
        migrations.AddField(
            model_name='projects',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Проект завершен'),
        ),
    ]
